GiteaBot/gitea-backporter

src/github.ts
src/mod.ts
src/webhook.ts

@techknowlogick not sure if we've established a workflow yet, making PRs to the origin and syncing here or making PRs here, etc?
Either way we're a bit out of sync at the moment.

Sync with upstream

---

src/github.ts
src/webhook.ts

This reverts commit 09004bab21a00641b2f57935ed4f86001c20309e and updates the trigger to use this fork.

Revert "Don't run automatically on commit (#56)"

---

src/mod.ts

Mention original PR author when adding a PR comment

---

.vscode/settings.json
src/github.ts

Also, force vscode to format using Deno

If there are 2 milestones with the same `major.minor` take only the earliest `patch`

---

src/github.ts

Remove GitHub actions trigger

---

src/github.ts

Request review from the original PR's approvers

---

src/backport.ts
src/git.ts
src/github.ts

It happened automatically on GitHub actions but now it's our responsibility

Set committer info

---

README.md
src/github.ts
src/mergeQueue.ts
src/webhook.ts

Backports are so old-news... We do all kinds of cool stuff now
Closes #6

Sync PRs in the merge queue and document new behavior in README

---

src/github.ts
src/github_test.ts

Fix fetching original PR approvers

---

src/github.ts

Update oldest PRs first

---

src/backport.ts
src/github.ts

Also removed unnecessary debug logs

Only target pull requests to `main` for backports

---

src/webhook.ts

The `secret` was supposed to be `!secret`

Fix initial environment variable check

---

src/mergeQueue.ts

Fix iterations on pending merge PRs

---

src/backport.ts

Initialize local git repo only once

---

README.md
src/github.ts
src/milestones.ts
src/webhook.ts

Milestone maintenance will make sure any unmerged pull request will not be part of any milestone.

Remove unmerged closed pull requests from milestones

---

src/mergeQueue.ts

Fix merge queue message logging

---

src/mergeQueue.ts

Hopefully this will stop the double updates

Debounce merge queue maintenance

---

src/lgtm.ts

This will look nicer on each approval

Report number of approvers in commit status

---

src/github.ts
src/github_test.ts
src/lgtm.ts

Now we have only one implementation counting reviews

Refactor to reuse approver calculation in backport review request and LGTM

---

src/github.ts

Send an array to GitHub, not a set

---

.github/workflows/deno.yml

These are just read-only tests, it's fine to run them

Run tests on PR

---

Dockerfile

I hope this will be more stable

Use debian instead of alpine

---

src/mergeQueue.ts

Iterate over all pull requests pending merge

---

src/cmd.ts
src/git.ts

See https://github.com/denoland/deno/discussions/9435
- Closes #7

Use `Deno.Command` instead of the deprecated `Deno.run`

---

src/webhook.ts

Review requests might change the approval count now
- Leftover from #75

Trigger `lgtm` whenever a review is requested

---

src/github.ts

Don't try to update open PRs

---

src/backport.ts

Better comment in case of backport failure

---

src/github.ts

It's fine to remove approvals by requesting reviews but we shouldn't remove change requests by requesting reviews
- Closes #104

Don't ignore change requests when the blocking user is requested to review

---

README.md
src/github.ts
src/labels.ts

Found @delvh are struggling with gitea bot. So ...
ref: https://github.com/go-gitea/gitea/pull/26984

Since kind/break -> pr/break in Gitea main repository, fix it in this repository

---

README.md
src/github.ts
src/lastCall.ts
src/webhook.ts

As stated in https://github.com/go-gitea/gitea/blob/main/CONTRIBUTING.md#final-call plus a week
- Closes #116

Close PR if it has not had any activity in the past 2 weeks and has `pr/last-call`

---

src/git.ts

Add an error log when a cherry-pick fails

---

src/github.ts

For debugging efforts
- Follows https://github.com/GiteaBot/gitea-backporter/pull/126

Add error log if `fetchMergedWithLabel` fails

---

src/github.ts
src/github_test.ts
src/state.ts

To avoid calling the github API so much

Cache the `backportPrExists` function

---

.github/workflows/ci.yml
.github/workflows/deploy-to-fly.yaml
.github/workflows/docker.yml
Makefile
README.md

- Add Makefile with dev tasks
- Clean up action files, remove unnecessary names
- Rename `deno` workflow to `ci`

Add Makefile, tweak actions

---

src/prActions.ts

A bit of weird logic.
Fixes #109

Don't post a merge conflict comment if another error happened
