GiteaBot/gitea-backporter

src/github.ts
Previous logging (afaict) logged some response items, but I think this is enough and is less likely to break if the response changes.
=> Use basic logging

src/github.ts
The calls are separated to allow the assignee call to fail and still let the milestone call to pass
=> If possible, set assignee to the original PR's author

src/github.ts
So https://github.com/go-gitea/gitea/pull/23852 won't happen again
Closes #20
=> Fix "null" being appended to the body in case the original PR didn't have a body

src/backport.ts, src/github.ts, src/labels.ts, src/webhook.ts
Closes #26
When PRs are merged there's no need for them to still have the `reviewed/wait-merge`/`reviewed/prioritize-merge` label.
Even though this codebase was originally intended to only handle backports, the foundations are laid to allow for label maintenance.
=> Remove `reviewed/wait-merge` and `reviewed/prioritize-merge` labels from merged PRs

README.md, src/backport.ts, src/giteaVersion.ts, src/github.ts, src/labels.ts
The script now removes all `backport/*` labels from pull requests that target release branches. The `giteaVersion` class now fetches milestones from the GitHub API for each gitea version. Finally, a `fetchTargeting` function queries the GitHub API for pull requests that target a specific branch.
=> Remove `backport/*` labels from PRs targeting release branches

README.md, src/labels.ts, src/webhook.ts
This makes the bot more flexible and responsive. We'll run backports only on `push` events to `main`.
Label maintenance and merge queue maintenance will be not only triggered only on `push` events but also on pull requests label events. To make sure we don't do too much unnecessary work, we only trigger these when either a `reviewed` or a `backport` label has been applied.
A new environment variable is introduced, `BACKPORTER_GITHUB_SECRET`. It'll be used to verify the requests are sent from GitHub.
- Closes #9 
- Part 1 of #38 (this change is required for that)
An octokit dependency is introduced for webhooks, we can later use the octokit SDK to query GitHub.
=> Allow to trigger on events other than `push` and secure the webhook

src/github.ts, src/github_test.ts, src/mergeQueue.ts
We now check if we need to update a PR and only do so if it's not synchronized already.
When the bot was triggered only on `push` this was unnecessary because all PRs became unsynchronized on `push`.
=> Don't sync PRs pending merge if they are already synced

.gitignore, src/github.ts
Also added a file to gitignore that I heavily use for local testing
=> Filter out labels from the pull-request-size bot when creating a backport

src/github.ts
This message should only be logged when `backport/done` is added, not when any label is added.
=> Fix logging of `backport/done` addition

src/github.ts, src/github_test.ts
The code assumed all PRs target the main branch. It now checks if each PR is synced against its base branch, not against the main branch.
=> Fix unnecessary branch updates to backport PRs

README.md, src/mergeQueue.ts
If, when updating PRs before merge, a merge conflict is detected, add a comment about it and remove the `reviewed/wait-merge` label from the PR.
=> Remove PRs with merge conflicts from the merge queue

src/github.ts, src/mergeQueue.ts
- Mention author
- Fix comment log
- Fix merge conflict detection (missed `break`), fixes #52
=> Fix conflict detection logic

README.md, src/github.ts, src/github_test.ts, src/lgtm.ts, src/webhook.ts
This will do the same thing the LGTM bot did more or less. We won't parse the `MAINTAINERS` file nor look for comments containing the word LGTM.
This is experimental as I couldn't really test it. Before this is merged, the old LGTM bot must be stopped. After this is merged, the context `backporter/lgtm` must be added to `go-gitea/gitea`'s required status checks in all protected branches (and `approvals/lgtm` removed).
If the `BACKPORTER_GITHUB_TOKEN` used for production doesn't contain the `repo:status` scope, it must be added before merging.
- Closes #50
=> Replace LGTM bot

README.md, src/milestones.ts, src/webhook.ts
Following a discord maintainer poll.
Also refactor to get PR details from the webhook instead of an additional API call.
=> Don't set the milestone automatically for PRs targeting `main`

src/mergeQueue.ts
I've observed mergers merging whatever pull request is pending merge, not in number order. So might as well make sure all pull requests pending merge are up-to-date.
Review without whitespace changes: https://github.com/GiteaBot/gitea-backporter/pull/67/files?w=1
=> Update all pull requests pending merge, not just the first one

README.md, src/milestones.ts, src/webhook.ts
We'll automatically set milestone for pull requests targeting release branches on creation and all pull requests on merge.
=> If a PR has no milestone when merged, automatically add it to a milestone

src/labels.ts, src/mergeQueue.ts
We sometimes trigger label maintenance too often, for example:
=> Debounce label maintenance and reduce wait time for merge queue debounce

README.md, src/github.ts, src/github_test.ts, src/lgtm.ts
We add a new `lgtm/blocked` state that makes sure no pull request gets merged while it still has changes requested.
- #73
=> Block pull requests as long as changes are requested

src/github.ts, src/github_test.ts, src/lgtm.ts
If a user is listed as a requested reviewer then their previous approval or block review is ignored. This pretty much matches GitHub's review view on a PR.
- Closes #74
=> Ignore anyone who is currently requested to review

README.md, src/github.ts, src/labels.ts, src/webhook.ts
Just a small addition because this can be automated
=> Make sure PRs that include `## :warning: BREAKING` in their body have the `kind/breaking` label

README.md, src/comments.ts, src/github.ts, src/github_test.ts, src/webhook.ts
This commit adds a new script that will comment on a pull request if it is opened with non-English translation files changed, directing the user to the crowdin project. Also added a new function that returns the list of files changed in the given PR number. Tests were included to test the new functionality.
Close #90
=> Direct users who add non-english translation changes to crowdin

src/webhook.ts
Locale backports are appropriate
Avoid commenting on PRs like https://github.com/go-gitea/gitea/pull/25635 and https://github.com/go-gitea/gitea/pull/25668
=> Only comment on translation changes if the PR is targeting `main`

README.md, src/backport.ts, src/comments.ts, src/github.ts, src/lock.ts, src/mergeQueue.ts, src/webhook.ts
We will lock issues and pull requests that have been closed for 3 months. If the issue was updated in the last month, a comment will be posted suggesting opening a new issue to continue the discussion.
The check is done on every push and will lock at most 30 issues at a time. We currently have ~400 issues awaiting for locking so the initial locking will happen over the next few days.
Closes #96
=> Lock issues closed for 3 months and pull requests merged/closed for 3 months automatically

README.md, src/lock.ts
- Reduced the time threshold for adding a comment from one month to two weeks.
- Adjusted the calculation of time thresholds in the `run` function of `lock.ts`.
- Updated the code comments to reflect the new time threshold.
Closes #96 (again)
=> Update locking script to add comments for issues updated within the last two weeks

README.md, src/github.ts, src/github_test.ts, src/lock.ts
- Added `fetchLastComment` function to retrieve the last comment of an issue
- Updated `run` function in `lock.ts` to use `fetchLastComment` to check the date of the last comment before adding a new comment
- Improved logic to determine if there is an active discussion before adding a new comment
Closes #96
=> Refactor locking logic to check the last comment date

README.md, src/labels.ts, src/mergeQueue.ts, src/prActions.ts, src/webhook.ts
This feature allows a maintainer to update a PR's branch by adding the `giteabot/update-branch` label. It is being removed after the update.
=> add ability to update PR by adding a label

src/github.ts
To avoid messages such as `{"message":"user doesn't have permission to update head repository","documentation_url":"https://docs.github.com/rest/pulls/pulls#update-a-pull-request-branch"}`
=> Check maintainers can modify before attempting to update

README.md, src/feedback.ts, src/github.ts, src/webhook.ts
We will close issues with the label `status/needs-feedback` if there is no new activity in the past month.
- Closes #106
=> Close issues with `status/needs-feedback` that were last updated more  than a month ago

README.md, src/feedback.ts
The label `status/needs-feedback` is now `issue/needs-feedback`.
- Fixes #113
=> Fix feedback label name

src/labels.ts
If a PR is successfully merged, there's no need to keep the `Last Call` metadata.
For unmerged closed PRs, this is different as there it is valuable information that it was only closed due to a lack of reviewers.
=> Remove `pr/last-call` label on merge

src/github.ts
To avoid creating a PR with `pr/last-call`.
=> Don't include `pr/*` labels when creating backports

src/git.ts
`stdout` and `stderr` have the type `Uint8Array`
=> Fix error log

src/github.ts
=> Check for existence of backport branch before trying to create it

src/github.ts, src/labels.ts
=> Add errors for `removeBackportLabelsFromPrs`

Dockerfile, README.md
Suddenly we need `--allow-sys` because octokit imports `https://esm.sh/v135/clean-stack@2.2.0/denonext/clean-stack.mjs`
I don't know why it's not pinned
=> Fix app crashing on fly.io

.github/workflows/deno.yml, deno.lock, src/backport.ts, src/labels.ts, src/milestones.ts, src/types.ts, src/webhook.ts
1. type checking (`deno check`) was not running on CI and there were 7 type errors which I've fixed and now it's running
2. GitHub API types are sourced from https://github.com/octokit/types.ts and I created basic types for `Issue` and `PullRequest`.
3. IDK about those two webhook errors, so I used `@ts-expect-error`.
4. `deno.lock` was auto generated, I guess it's good to have it in-repo. 
5. `actions/checkout` is upgraded to latest major.
=> Run typecheck on CI and fix issues

.dockerignore, .github/workflows/deploy-to-fly.yaml, Dockerfile, deno.json, deno.lock, src/giteaVersion.ts, src/github.ts, src/github_test.ts, src/labels.ts, src/mergeQueue.ts, src/milestones.ts, src/prActions.ts, src/types.ts, src/webhook.ts
- Add deno.json with import maps
- Load the standard library from jsr as that seems [recommended nowadays](https://docs.deno.com/runtime/manual/basics/import_maps/#example---using-the-deno-standard-library) and I find it more managable than to have versions in each file.
- Bump standard library from 0.189.0 to 0.196.0 because that is the oldest version available on jsr.
=> Add import maps and import standard library from jsr

README.md, src/lastCall.ts
If a week has passed since the final call, add a comment reminding TOC to review.
**This requires a new label to be added `giteabot/toc-reminded`.**
- Closes https://github.com/GiteaBot/gitea-backporter/issues/136
=> Remind TOC to review PRs with `pr/last-call`

src/github.ts, src/labels.ts
From the logs:
```log
2024-10-19 15:52:16.292	error: Uncaught (in promise) Error: removeBackportLabelsFromPrs called with undefined
2024-10-19 15:52:16.292	throw new Error("removeBackportLabelsFromPrs called with undefined");
2024-10-19 15:52:16.292	          ^
2024-10-19 15:52:16.292	at removeBackportLabelsFromPrs (file:///app/src/labels.ts:83:11)
2024-10-19 15:52:16.292	at file:///app/src/labels.ts:76:12
2024-10-19 15:52:16.292	at eventLoopTick (ext:core/01_core.js:175:7)
2024-10-19 15:52:16.292	at async Promise.all (index 1)
2024-10-19 15:52:16.292	at async Promise.all (index 1)
2024-10-19 15:52:16.292	at async Function.maintain (file:///app/src/labels.ts:26:3)
```
- Follows https://github.com/GiteaBot/gitea-backporter/pull/129
=> Add debug logs for `removeBackportLabelsFromPrs`

src/labels.ts
It was rate-limiting.
- Follows https://github.com/GiteaBot/gitea-backporter/pull/138
=> Catch an error instead of crashing
